[ui]
dark = false # toggle dark theme
injections = "" # inject rules into the CSS file.
save_sidebar_widths = true # save widths between restarts?
[ui.center_toolbar_items]
in_normal = false
in_fullscreen = true

[behavior]
persist_media_on_sort_change = true # If true, change the media index to keep the shown media the same when the sort method is changed. If false, keep the index the same, changing the media
[behavior.history]
save_history = true # save TagSpace history? (for Recently Opened)
auto_resume = false # if a previous TagSpace is saved, should it be opened automatically? (depends on save_previous)
[behavior.tagspace_defaults]
tags = [
    ["Favorite", "#fed330"],
    ["Low-Quality", "#26de81"],
    ["Important", "#fd9644"]
]
props = [
    ["Description", "String"]
]
[behavior.slideshow]
interval = 2000 # milliseconds per item in the slideshow
end_on_fullscreen_exit = true # end the slideshow when you exit fullscreen
stop_at_end = false # end the slideshow when the last item is reached (if false, wrap around)
